- ros_topic_name: /lidar_points
  gz_topic_name: /world/default/model/x500_lidar_2d_0/link/link/sensor/lidar_2d_v2/scan/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS

- ros_topic_name: /scan
  gz_topic_name: /world/default/model/x500_lidar_2d_0/link/link/sensor/lidar_2d_v2/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS

- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
